//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricityUseReportService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReading
    {
        public short BuildingId { get; set; }
        public byte ObjectId { get; set; }
        public byte DatafieldId { get; set; }
        public decimal Value { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
